/-
Proves involving finite series are quite common in mathematics. Here, let's try to prove the
formula for the sum of the first `n` natural numbers is n * (n + 1) / 2.
-/

-- To have access to summation tools, we need to import the Mathlib library.
import Mathlib


theorem gauss_summation (n : ℕ) : ∑ i ∈ Finset.range (n + 1), i = n * (n + 1) / 2 := by
  induction n with
  | zero => simp
  | succ n ih =>
    rw [Finset.sum_range_succ, ih]
    rw [Nat.add_assoc, Nat.mul_add (n + 1), Nat.add_div (by trivial)]
    -- To eliminate the `if` condition generated by `Nat.add_div`, we need to prove that
    -- `(m + 1) * m` is even. We do that by defining a helper lemma `h1` and proving it by
    -- induction.
    have h1 (m : Nat) : (m + 1) * m % 2 = 0 := by
      induction m with
      | zero => simp
      | succ m ih =>
        rw [Nat.add_assoc, Nat.add_mul, Nat.add_mod, Nat.mul_comm, ih]
        simp
    -- Now we can simplify the expression using the fact that `(m + 1) * m` is even.
    simp? [h1]
    rw [Nat.mul_comm]

/-
Helper lemmas can be defined inside a proof using the `have` keyword, as we did with `h1`, or as
separate top-level lemmas outside the proof. The choice depends on whether the lemma is useful only
within the proof or more generally.
-/
